### ISSUE TITLE
menu: NVDA + Firefox only opens once

### ISSUE THREAD

**Issue by ryanflorence** [reach/reach-ui#1]
In NVDA if you open the menu with the keyboard, close it with escape, and then try to open it again with the keyboard it won't open.

It's fine if you open, close, tab away, tab back, open.

Also this might be related: https://spectrum.chat/thread/7e8cbbd4-cebf-4555-8c6e-61f96e1354ad?m=MTUzNTM2NTA2MTc5MA==

**Comment by venikx** [comment]
Hey @ryanflorence I tried reproducing the issue today, but I couldn't reproduce it. 
So either I'm doing something wrong or the issue is irrelevant in the current state of the codebase.

Steps I followed:
1. Downloaded NVDA from https://www.nvaccess.org/download/
2. Installed NVDA and enabled the voice-over
3. Started Storybook and tried reproducing the bug following your steps

If this is correct I think we can close the issue?
