### ISSUE TITLE
Overriding styles of DialogOverlay and DialogContent requires increased specificity

### ISSUE THREAD

**Issue by ooloth** [reach/reach-ui#116]
Thanks for this library! 🙌

I just wanted to report that overriding the default styling of `DialogOverlay` like this...

```js
import styled from 'styled-components'

const Overlay = styled(DialogOverlay)`
  background-color: hsla(0, 100%, 100%, 0.9);
`
```

...does not work (the default styling wins). 

However, increasing the specificity fixes the issue:

```js
const Overlay = styled(DialogOverlay)`
  && {
    background-color: hsla(0, 100%, 100%, 0.9);
  }
`
```

The same issue exists with `DialogContent`.

This isn't a huge deal, but the first option would be nice to have if possible.

**Comment by amberleyromo** [comment]
^Same with `MenuButton`

**Comment by danieltott** [comment]
Until [the :where pseudo-class](https://drafts.csswg.org/selectors-4/#zero-matches) is available, there is just no way to get around this while still importing static css files. Attribute selectors and class selectors have the same specificity, which is why (sometimes) you'll see the default styles from the css being overwritten. I say "sometimes" because there's no way to predict which order a bundler/runtime will output css rules. I [created a codesandbox](https://codesandbox.io/s/competent-sea-4icmy) illustrating this problem. When you open it, the background override _does_ take effect, but as soon as you start editing the file, the override stops working. This is because the codesandbox's dev server combined with `styled-components` in `development` are loading things in dynamically, and the order gets swapped around.

The only true solution to allow users of `styled-components` to override styles in this way without bumping up specificity would be to rewrite reach-ui using `styled-components`, which isn't an option. 

One last note, if you wanted to avoid doubling the specificity of your selector by using `&&`, you could use an element selector to just bump it up a bit:

```js
const Overlay = styled(DialogOverlay)`
  div& {
    background-color: hsla(0, 100%, 100%, 0.9);
  }
`
```

This seems closable to me.
