### ISSUE TITLE
Dialog closing with Transition

### ISSUE THREAD

**Issue by cristianfraser** [reach/reach-ui#120]
When using the Animation Example on the `Dialog` doc page, I'm facing an issue.

When disappearing, click events take a little to be enabled again, because of the focusTrap. I'm guessing only when it completely disappears and is unmounted, the trap stops working.

But, is it possible for this case, that `Overlay` (or the component in charge of rendering the `Portal`) could disable its focusTrap while it is being unmounted, rather than after unmounted?

**Comment by bradwestfall** [comment]
Hi @cristianfraser, thanks for the issue. Is this a dup of #206

**Comment by bradwestfall** [comment]
Sounds good @cristianfraser. We're putting a bunch of work into this lib as of recently so we'll make our way around to this. Thank you for posting

**Comment by stephan281094** [comment]
Not sure if related to this issue or to #206, but something similar happens when opening the dialog. The `initialFocusRef` will get focus *after* the transition is done. This means that when a user focuses another input while the transition is still happening, it will eventually "steal" the focus (see https://youtu.be/mw9RaALIlbc).
