### ISSUE TITLE
update build process to newer stuff

### ISSUE THREAD

**Issue by ryanflorence** [reach/reach-ui#123]
Pretty sure we're on old babel, lerna, storybook.

Would love if somebody who is better at this stuff than me could figure out how I've got it setup, and update it.

Storybook is SO DANG SLOW so I've been just including the one example that I'm working on. Would love if this was fast. I'm okay ditching storybook and just pointing Parcel at a `reach-ui/playground/index.html`. Just something that lets us throw code at it and run it in the browser.

I tried that with parcel but all the babel stuff is old so it has errors like "Plugin/Preset files are not allowed to export objects, only functions."

Also, the `release` package.json script doesn't really work. I've been manually doing:

```
lerna run build --parallel --since <copy/paste last release sha>
lerna publish --since <copy/paste last release sha>
```

Would love to know a better way for that.

Finally, I wonder if we should just use `microbundle` for the build step on everything?

Anyway, I would merge any PRs that updates all the babel/storybook stuff that is builds super fast between file saves, or updates babel and makes a really simple playground with Parcel.

Thanks!

**Comment by jakiericecox** [comment]
@ryanflorence I will try to set aside some time this weekend to work on this. I love working on tooling setup like this, but I'm real swamped with Spring Break stuff right now. I'll definitely give it a look if someone doesn't pick it up before me.

**Comment by jakierice** [comment]
Oops...that was my work account. Is there any way to delete that ^^^ comment?

**Comment by jakierice** [comment]
@ryanflorence sorry for blowing you up with notifications. I had to remove my initial comment from my work account.

I will try to set aside some time this weekend to work on this. I love working on tooling setup like this, but I'm real swamped with Spring Break stuff right now. I'll definitely give it a look if someone doesn't pick it up before me.

**Comment by pshrmn** [comment]
My Lerna (v3) setup uses local file specifiers for dependencies, which removes the need for `lerna bootstrap` and moves every dependency to a root `node_modules`. (`lerna publish` converts the local file specifiers to real dependency values.)

```bash
npx lerna link convert
```

Versions are updated using `lerna version` (I have some post-version scripts that I run, which is why I skip creating a commit).

```bash
lerna version --no-git-tag-version --no-push
```

Then publishing is done by only publishing packages whose versions don't exist on the registry.

```bash
lerna publish from-package
```

With this setup, everything gets run from the root directory. When I'm working on a specific package, I end up using `npx lerna exec --scope=<package name> -- <comand>`. It is a bit verbose, but I've gotten used to it.

The only real catch that I've run into with local file specifiers are example packages that can be run on CodeSandbox, but I didn't notice any of those in this repo.
