### ISSUE TITLE
[Combobox] duplicate values prevent arrow navigation

### ISSUE THREAD

**Issue by aweary** [reach/reach-ui#216]
## Spark Notes Summary

If there are two `ComboboxOption`s with the same `value` it prevents you from navigating past them with the arrow keys.

## Prove It

* Go to [this Codesandbox](https://codesandbox.io/s/reach-combobox-duplicate-value-arrow-bug-si10y)
* Focus the input and type "A"
* Focus the first "Apple" result by pressing the down arrow key
* Attempt to focus the next result by pressing the down arrow key again

## What Happens?

Focus does not move. You can kind of work around this by pressing *up* and wrapping around the whole list but that sucks

## What Should Happen?

I don't really know, maybe it should skip the next "Apple" value and select the next unique option after that? Having duplicate values is generally a bad experience since it can move focus and trap you in this weird focus cycles. Maybe the answer is just "don't have duplicate values"?

**Comment by chrstntdd** [comment]
I hit this bug as well when messing around with the combobox, but part of me thinks that it should definitely be the responsibility of the dev to filter out duplicate values before rendering them so as not to confuse end users with multiple seemingly identical - yet distinct choices. 

Since the combobox active-descendant is not being derived from the item's index - this seems unfeasible given the design decisions Ryan made [here](https://github.com/reach/reach-ui/blob/master/packages/combobox/src/index.js#L693).

**Comment by aweary** [comment]
I think it would be solvable by using a combination of the value and index to uniquely identify options, and then using `findIndex` to calculate the index instead of `indexOf`.

It's totally up to the product developer to provide unique values but I'm 99% sure many people will accidentally have duplicate values _eventually_ and it'd be cool if it didn't result in super confusing behavior for the user. Maybe checking for duplicates in DEV and using `React.error` or React.warn` to call them out would be a nice way to prevent that.

**Comment by chrstntdd** [comment]
That's a great idea! If @ryanflorence is into it - I'd love to contribute!

**Comment by fnky** [comment]
I don't think this should be the job of the Combobox itself. In my opinion it should work like the `key` prop and not allow duplicate values by throwing an error that explains this in detail.
