### ISSUE TITLE
[Combobox] Tab to select

### ISSUE THREAD

**Issue by Daniel15** [reach/reach-ui#233]
With autocompletion components, selecting an item with the keyboard arrow keys then pressing tab usually selects it and moves focus to the next input field. However, with the react-ui "combobox", this is not the case - Pressing tab does not select the item, instead you need to press enter. Is that an intentional design decision?

Related, from 2016: https://github.com/reactjs/react-autocomplete/issues/182
Examples of autocompletion components where pressing tab selects the item then goes to the next input field:
 - https://jedwatson.github.io/react-select/
 - http://react-autosuggest.js.org/
 - https://harvesthq.github.io/chosen/
 - https://jqueryui.com/autocomplete/
 - http://easyautocomplete.com/

I have a web page with an autocompletion component where selection behaves differently when selected via enter vs when selected via tab. The way I solved that years ago with react-autocomplete was by adding a `selectionMethod` field argument to the onSelect method, specifying whether it was enter or tab that caused the selection.

**Comment by venikx** [comment]
Hi @Daniel15 

The library seems to follow the [WAI-ARIA](https://www.w3.org/TR/wai-aria-practices-1.1/#combobox) spec closely. The spec defines the behavior for a combox, when the list box is active as follows:

> Enter: Accepts the focused option in the listbox by closing the popup and placing the accepted value in the textbox with the input cursor at the end of the value.

Whenever the list box is active from the combobox there is no behavior specified for TAB. I'd consider it as intentional design.

**Comment by fnky** [comment]
Yeah, I also believe this is intentional. If you use tab on native controls like `select`, with a the menu open, it will either focus away from the control to the next target or not do anything at all. 

This may be OS specific, but I don't know. On macOS, pressing tab with a menu open doesn't do anything, for example.

Tab is for _navigation_ rather than _selection_.

**Comment by eldh** [comment]
I understand why this might be the correct & intended behaviour, but I think it becomes a bit confusing when `autocomplete={true}` on `ComboboxInput`, since the input has the selected value before tabbing away. If there was a way to visually differentiate a temporary input value from a "committed" value I think it would improve the experience.

**Comment by venikx** [comment]
Can you record a gif or something, because I’m not sure I follow.
It sounds like a separate issue/bug though.

**Comment by eldh** [comment]
Oh sorry, I don't think it's a bug, I think it's the intended behaviour. Maybe these make it a bit more clear what I mean?

This is the behaviour with autocomplete=false (click the input -> arrow down -> tab):
![autocomplete false](https://user-images.githubusercontent.com/612703/64415138-0be87900-d095-11e9-90b9-5f9857d3779c.gif)

autocomplete=true:
![autocomplete true](https://user-images.githubusercontent.com/612703/64415139-0be87900-d095-11e9-88b8-078cabb8391a.gif)

**Comment by venikx** [comment]
Awesome gif. Really explains a lot. The autocomplete behavior indeed looks fine, but I wonder why it’s skipping the style input? Did you do anything specific to skip the focus?
If not that looks like a new bug.

**Comment by venikx** [comment]
Najs! That explains a lot. 
Not sure what autocomplete is supposed to act like according the spec of the combobox, since I can’t really find it (currently on mobile so a bit hard to navigate quickly).

Personally I’d expect Font to be pre-selected with Open Sans and when you tab away that means it should keep the value of Open Sans. So I think it’s working unexpectedly, but it might be according to the spec (feels weird tho).

Another thing I noticed is that the form skips a field. It jumps to the font size field and skips the Style field. Is that something you did on purpose? If not it seems like another bug.

**Comment by eldh** [comment]
Oh, the Style input there is next on my list to fix, it's not a problem with combobox at all. 🙈

**Comment by venikx** [comment]
Could you create a separate issue with the autocomplete behavior not working as expected, since I think it’s separate question/bug. If I could I’d have closed this issue already.

**Comment by eldh** [comment]
Sure! Created https://github.com/reach/reach-ui/issues/268
