### ISSUE TITLE
Question: @reach/tabs - How to switch all tabs at once on the page

### ISSUE THREAD

**Issue by gaurav-nelson** [reach/reach-ui#238]
If I have a page with mutiple tabs with same labels:
```
Heading 1

First tab block
Tab 1 | Tab 2
Content Tab 1

Second tab block
Tab 1 | Tab 2
Content Tab 1 for second block

Third tab block
Tab 1 | Tab 2
Content Tab 1 for third block
```

What I want is that when I switch to "Tab 2" all tabs on page should switch to "Tab 2". 

Any pointers on how to achieve this?

**Comment by venikx** [comment]
Hi @gaurav-nelson,

That sounds like the job for a controlled behavior of the tabs component. That means that you'll have to manage the index yourself. You can find more info [here](https://ui.reach.tech/tabs#tabs), but I can give a TL;DR.

```react
<Tabs
  index={tabIndex}
  onChange={idx => setIndex(idx)}
/>
<Tabs
  index={tabIndex}
  onChange={idx => setIndex(idx)}
/>
```

Personally I'd consider the behavior a bit odd, but probably you'll have a good reason to do so.

**Comment by gaurav-nelson** [comment]
Thank you @venikx 

I thought that behavior was common. The use case is somewhat similar to the code selection tabs available at https://guides.gradle.org/building-java-applications/  if you select 'Kotlin' all following code block will show 'Kotlin' code samples.

**Comment by venikx** [comment]
@gaurav-nelson I would certainly consider that a cool use-case indeed ^^

**Comment by gaurav-nelson** [comment]
Thank you for your help earlier, I spent some time trying this out. I am trying to create a Tab component for a Gatsby site. 
1. I created a 'CoLocatedTabs' component (with controlled behavior)
Code: https://github.com/gaurav-nelson/gatsby-gitbook-starter/blob/master/src/components/tabsTest.js
2. Imported it into MDX (twice)
Code: https://raw.githubusercontent.com/gaurav-nelson/gatsby-gitbook-starter/master/content/introduction.mdx
3. In rendered version I get two separate tab components which don't talk to each other. 

I understand that both components are different and have there own index. Is there anyway to globally handle index for all tabs component on a page?

I know this is not an issue about @reach/tabs so feel free to close this issue as my original question was answered. However, I'll appreciate any help that can help me resolve this.

**Comment by venikx** [comment]
I’m not too familiar with mdx, but it looks like you can only import components. That’d mean you’ll have to create a CombinedTabListManager which abstracts away the logic you want to achieve with multiple Tabs, same index.So basically you’d need to import the combined tab component once in mdx and that one should manage the index of your multitab component.

Unless there is a way to keep the state in mdx, but I haven’t played around with mdx at all. So not sure about it.

I hope that helped. Regarding closing the issue, I’d recommend closing it yourself (if you can), because I’m unable to close it unfortunately.

**Comment by gaurav-nelson** [comment]
Thanks, I'll try that out.
