### ISSUE TITLE
Menu component doesn't pass custom styles

### ISSUE THREAD

**Issue by NerdCowboy** [reach/reach-ui#242]
**Expected behavior:**
Allow class overrides to be passed to the Menu component

**Actual Behavior**
No class overrides are passed to the Menu component

Using CSS Modules, I have this:
```
<Menu className={styles.test}>
  <MenuButton className={styles.dropdownButton}>
    Actions  
  </Menu Button>
  <MenuList>
    (… dropdown content here)
  </MenuList>
</Menu>
```
All other components appear to pass in classes as expected.

This is slightly related to https://github.com/reach/reach-ui/issues/67 as the reason I'm trying to add class overrides is due to some z-index issues. The MenuButton is in a fixed header that has a higher z-index to make sure it's above everything, but due to this, the menu list is appearing underneath the header. 

Regardless, I'd still expect to be able to pass in overrides there to do things like make a minor adjustment to the positioning (i.e. shift the menu list slightly downward to line up with the header)—though that probably could be solved better with offsetX/Y props.

**Comment by venikx** [comment]
@NerdCowboy 

It doesn't makes sense to allow class override to be passed to the `<Menu />` component, because the MenuComponent itself doesn't render anything. It acts like a state container and managing some internal stuff, but the rendering is done by the children. So in that sense it's normal/expected that you can't style the `<Menu />` component.

If you want to style the button you can do that in `<MenuButton />` and if you want style the list, dropdown, ...  (the menu which pops up after clicking the button) you can do that in `<MenuList />`. 

I recommend trying out placing the `styles.test` on the `<MenuList />` component.

**Comment by NerdCowboy** [comment]
@venikx When you said it doesn't render anything, I'm a little confused. On the main example, this is what is rendered at the top level in the html.
`<div data-reach-menu="true" style="left: 351px; top: 926.25px; min-width: 77.2px;"></div>`

So it appears it's rendering something in the DOM —unless you mean it's not rendering anything that's visible since it's just a wrapping element.

As you mentioned, I was able to adjust the positioning issue I mentioned by targeting the MenuList element. 

However, the z-index issue remains (https://github.com/reach/reach-ui/issues/67) as that can't be solved by styling anything that's a child of that element. But it could be solved by allowing a user to pass a higher z-index to that wrapping Menu element via style overrides.

So I was able to solve my z-index issue by globally targeting the `[data-reach-menu]` element, but that's not ideal when working with CSS Modules or CSS in JSS solutions.

**Comment by venikx** [comment]
The `<Menu />` component is only responsible for handling state, it's a state container, or it's logic probably could be rewritten using hooks. You can find the implementation here: https://github.com/reach/reach-ui/blob/master/packages/menu-button/src/index.js#L88

The component you are talking about (the one that creates the `data-reach-menu`) is defined by the `<MenuList />`, which is creating a portal for the dropdown. 

The z-index issue might be a deeper issue. The reason why you were unable to set the styles correctly is that props passed into `<MenuList />` (so in your case `className`) get spread out "too late" to properly set the z-index. Notice here: https://github.com/reach/reach-ui/blob/master/packages/menu-button/src/index.js#L326 how it would be fine there would be a way to style the `div data-reach-menu />`.

**Comment by NerdCowboy** [comment]
Ok, makes sense. Appreciate you taking the time to explain. I'll follow #67 to see where they end up with that. Thanks!

**Comment by venikx** [comment]
No problem mate! The issue in https://github.com/reach/reach-ui/issues/67 seems a bit more complex than the issues I'm currently comfortable with. I just started exploring and digging into the codebase. 
I'll you know if I find something that could get rid of your globally defined style at least ^^

**Comment by venikx** [comment]
@NerdCowboy One way I see this solved, but it depends a lot if Ryan didn't want to make it customizable on purpose or not. It could be possible to apply styles on: https://ui.reach.tech/menu-button#menulist by having a prop which targets the [data-reach-menu] specifically. 
At the moment it's also not possible (not aware of at least) to customize the styling of the container itself. For example it's width. But it depends if Ryan want to expose this customization or not. 

The other way (since it seems very specific to the z-index case) would be to solve like proposed in https://github.com/reach/reach-ui/issues/67, which upon the `data-reach-menu` would read it's value and set it's own index accordingly. 

But again, not sure what would be a correct way forward.

**Comment by bradwestfall** [comment]
Sounds resolved to me, let me know if you need it opened up again
