### ISSUE TITLE
Tooltip children onFocus doesn't work

### ISSUE THREAD

**Issue by roblotter** [reach/reach-ui#248]
Having onFocus on a tooltip child won't work

```jsx
<Tooltip><button onFocus={....} /></Tooltip>
```

the `onFocus` on the button is never triggered

**Comment by venikx** [comment]
Most likely fixed by: https://github.com/reach/reach-ui/pull/226

**Comment by chancestrickland** [comment]
Fixed in https://github.com/reach/reach-ui/pull/226

**Comment by venikx** [comment]
@chancestrickland Hmm, I remember specifically testing that change to be sure and it didn't fix it. Not sure if there was something else going on. 

If you think about what was happening before that change is the following: The passed in `onFocus` handlers gets triggered by a blur event and a focus event. The #233 fixed it so the on a blur event, that it only calls the passed in `onBlur`, so it's not a fix for this issue I think.

I'll test it again later during the week, I might be wrong.

**Comment by chancestrickland** [comment]
@venikx I will do another pass but if you have a moment before I get to it, feel free to wave the flag again and I'll re-open then issue.

**Comment by venikx** [comment]
@chancestrickland It's not fixed! 
![Recording which shows that adding a onClick handler to a `<button />` inside the `<Tooltip />` component works, but onFocus doesn't get triggered.](https://media.giphy.com/media/QtqApj2S3916fQLcRn/giphy.gif)

**Comment by venikx** [comment]
I found out why, but not sure what the correct way forward would be.
If you look at https://github.com/reach/reach-ui/blob/master/packages/tooltip/src/index.js#L370
you see that `useTooltip` exposes trigger props.

These trigger props get passed onto the element generated by cloneElement. However, in order to get any of the handlers working that are defined by the "trigger" you need to pass in these elements to the `useTooltip` hook. 

So I assume `onMouseEnter`, `onMouseMove`, etc (all trigger props) have the same issue.

**Comment by chancestrickland** [comment]
@venikx Events on the trigger appear to be working: https://codesandbox.io/s/tooltip-event-test-dfmz1
