### ISSUE TITLE
MenuButton (Dropdown) goes off-screen on Mobile

### ISSUE THREAD

**Issue by CharlyMartin** [reach/reach-ui#262]
Hello Reach UI 👋

I'm using your `MenuButton` (https://ui.reach.tech/menu-button/) component and it goes off-screen on mobile.

I noticed that the position of the list is injected on the parent element, like `style="left: 323px; top: 336px; min-width: 20px;"`.  That works fine when there's enough space on the left, but on mobile it goes off-screen: https://jngl.pm/kpuyJLY6

I couldn't find this edge case in your docs. Is there a way to prevent that from happening? Is Dan still in here?? 😆 

Cheers 🙂 

For reference, my Dropdown component:

```
import React from "react";
import { createGlobalStyle } from "styled-components";
import { Box } from "rebass";

import theme from "../theme/theme";
import {
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
  MenuLink
} from "@reach/menu-button";
import "@reach/menu-button/styles.css";

const Dropdown = Menu;
const DropdownButton = props => <MenuButton {...props} />;
const DropdownList = MenuList;
const DropdownItem = MenuItem;
const DropdownLink = MenuLink;

const DropdownStyles = createGlobalStyle`
  & * {
    box-sizing: border-box;
  }

  /* Button */
  [data-reach-menu-button] {
    display: flex;
    align-items: center;
    border: none;
    background: transparent;
    border-radius: 3px;
    padding: 0;

    /* Button - Open state*/
    &[aria-expanded="true"] {
      background: ${theme.colors.orange.main};
      color: white;
    }
  }

  /* List */
  @keyframes slide-down {
    0% {
      opacity: 0;
      transform: translateY(-10px);
    }
    100% {
      opacity: 1;
      transform: translateY(0);
    }
  }

  [data-reach-menu-list] {
    position: relative;
    z-index: 2;
    border-radius: 3px;
    animation: slide-down 0.2s ease;
    padding: 5px !important;
    box-shadow: ${theme.shadows.large};
  }

  /* Item */
  [data-reach-menu-item] {
    padding: 5px !important;

    /* Item - Selected*/
    &[data-selected] {
      /* background: ${theme.colors.orange.light} !important; */
      background: none !important;
      /* color: ${theme.colors.black} !important; */
      color: inherit !important;
    }

    &:hover {
      background: ${theme.colors.orange.light} !important;
      color: ${theme.colors.black} !important;
    }
  }
`;

const DropdownContainer = props => {
  const { children, ...rest } = props;

  return (
    <Box {...rest}>
      <DropdownStyles />
      <Dropdown>{children}</Dropdown>
    </Box>
  );
};

export {
  DropdownContainer,
  DropdownButton,
  DropdownList,
  DropdownItem,
  DropdownLink
};
```

**Comment by christiankaindl** [comment]
Mhm... I also use a MenuButton, but the collision detection works here.

From looking at your code, maybe you are missing some of the default styles? Like that one:
``` css
[data-reach-menu] {
  font-family: sans-serif;
  display: block;
  position: absolute;
}
```
I don't see it in your code sample above. For reference, all MenuButton default styles are here: https://github.com/reach/reach-ui/blob/master/packages/menu-button/styles.css

The default styles are a bit weird to me, because some of them are required for the component to even work (like a `position: absolute`), and some (like `box-shadow`) are not. And they are not separated. So, I always copy/paste all of them and then remove the unnecessary default stylings, but keep the essential properties. For more info, see: https://ui.reach.tech/styling

**Comment by CharlyMartin** [comment]
It seems to be working 😄  Thanks @christiankaindl! I inherited this code so I assumed the setup was right, but this was the missing piece 🙌

**Comment by mrm007** [comment]
@CharlyMartin you *are* importing the MenuButton styles -- see line 13. The issue here is the one described in reach/reach-ui#189. Sadly, @ryanflorence is too busy to review that one line PR so you'll have to "vendor" the `menu-button` package to get the fix. Here's a [condescending tweet](https://twitter.com/ryanflorence/status/1139552733029998592) with the necessary steps.
