### ISSUE TITLE
[ComboBox] Autocomplete value is cleared when tabbing away from combobox

### ISSUE THREAD

**Issue by eldh** [reach/reach-ui#268]
See discussion in #233. 

Problem is this: The input value is reset to its old value after pressing tab, which I assume is the intended behaviour, but it feels a bit counterintuitive to me when `autocomplete=true`. With `autocomplete=false` the input value is never set, so it makes more sense that pressing tab does not change the value.

I can think of two solutions – either set the value on tab if `autocomplete=true`, or add something like `data-temp-value` to the input so that I could give it a different styling before the value is actually "committed".

Some gifs (input sequence is click input -> [down arrow] -> tab):

autocomplete=true
![autcomplete on](https://user-images.githubusercontent.com/612703/64424863-85d72d00-d0aa-11e9-846a-d837f0707af1.gif)

autocomplete=false
![autocomplete off](https://user-images.githubusercontent.com/612703/64424864-85d72d00-d0aa-11e9-99a9-79104cb9382e.gif)

**Comment by venikx** [comment]
Hmm, after reading into it a bit better the problem seems to be a bit bigger. There is conflict in the api exposed by `reach-ui` and the regular HTML input api (see https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete). 
That's also why I was confused in #233, but now it makes sense. 

The HTML spec for autocomplete is to provide a way for browsers to pre-fill previous filled input fields with same types. 

The `reach-ui` version of autocomplete is (true/false), which is an incorrect value for the autocomplete property and talks about (not) changing the value of the input upon focusing an element of one of the options. 

In the `reach-ui` sense of the autocomplete API it does seem like broken behavior, because it's not doing what is said in the docs. So that's a bug for sure.

I'd like to propose a breaking API change, to get rid of autocomplete as part of the ComboboxInput api and supposed to be spread via the props on the input element itself (since autocomplete define how the browser auto-complete a form, when using lastpass or something).

The a11y spec has an example here: https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html so maybe we can react based on `aria-autocomplete="both"`?

**Comment by eldh** [comment]
Yeah it makes sense to change, since the `autocomplete` attributes conflicts with native browser behaviour like you said.  The behaviour in the `aria-autocomplete="both"` is what we want I think.
