### ISSUE TITLE
Fix issues with how IDs are handled

### ISSUE THREAD

**Issue by chancestrickland** [reach/reach-ui#321]
### Current Behavior

There are a few places in the project where IDs are auto-generated on the client. This may be undesirable for a few reasons (users who disable JS lose important accessibility features, potential race condition bugs when used with non-React libs, two examples).

Further, in our auto-generated IDs we often use colons as delimiters. `document.querySelector` throws an error when receiving a string with a colon.

```
document.querySelector('#id:1')
SyntaxError: '#id:1' is not a valid selector
```

### Expected behavior

We should 1) allow users to set IDs via props everywhere we are generating them currently, and 2) we should remove colons from our generated IDs.

**Comment by danieltott** [comment]
@chancestrickland The first part makes sense, but can you point out where there are colons in generated IDs? I have found three components that use generated IDs: alert-dialog, menu-button, and skip-nav (although with skip-nav it's not generated, it's hard-coded). But it seems like when creating an ID, they're being concatenated with `-`, not `:` (``labelId: `alert-dialog-${genId()}`,`` for example. I'm sure I'm missing something because I'm still getting my bearings in the source code.

**Comment by chancestrickland** [comment]
@danieltott Sounds good -- I created a new branch for this but that's as far as I've gotten. Happy to take a look when you have a PR ready.

**Comment by danieltott** [comment]
@chancestrickland For updating components to allow for ID overriding, would it make sense to create a series of PRs per Reach component? Or would you prefer a single, larger PR?

**Comment by chancestrickland** [comment]
@danieltott Single PR is fine. We typically release all at once and only the updated packages will get a version bump.

**Comment by chancestrickland** [comment]
@danieltott We try to handle attributes like `aria-controls` automatically, so even if the user passes their own ID to the input they shouldn't need to worry about its controller component. In this particular case we still need to allow the user to pass an ID for combobox (working on that one), but I don't see any value in allowing them to override `aria-controls`.

**Comment by danieltott** [comment]
@chancestrickland Sounds good. I should have a PR up early this week.
