### ISSUE TITLE
[MenuButton] Chrome tries to scroll to items, even when it can't

### ISSUE THREAD

**Issue by cpmsmith** [reach/reach-ui#369]
### Current Behavior

When the contents of the menu overflow downward, Chrome attempts to scroll the whole menu onto screen when you mouse over items. If the menu is attached to something whose position is fixed, it just repeatedly scrolls the page downward past all the actual content. Firefox doesn't do the same thing.

### Expected behavior

At least not doing the scrolling. It could conceivably limit the `max-height` of the menu to fit on screen, but that might be outside the scope of the implementation.

### Reproducible example

https://codesandbox.io/s/frosty-sunset-mdmkg

### Your environment

| Software                 | Name/Version(s) |
| ------------------------ | --------------- |
| @reach/menu-button  | 0.5.4 |
| React                    | 16.11.0 |
| Browser                  | Chrome M78 |
| Operating System         | macOS 10.14.6 |

**Comment by chancestrickland** [comment]
Hmm. I'm not 100% how we should approach something like this at first glance. The menu itself is in a portal, so it isn't inside of the fixed container (hence why it triggers scrolling). I'm not sure if your expected behavior would necessarily be the generally expected behavior, but it's worth considering for sure.

In the mean time, overriding the menu's position to `fixed` seems to, errr... fix it. So in your project you might do:

```css
[data-reach-menu] {
  position: fixed !important;
}
```

If you don't want other menus to be fixed you can use the composeable menu API and do:

```jsx
<Menu>
  <MenuPopover className="fixed-menu-button">
    <MenuItems>{...}</MenuItems>
  </MenuPopover>
</Menu>
```

```css
.fixed-menu-button {
  position: fixed !important;
}

**Comment by cpmsmith** [comment]
Yeah, I'm generally not sure what behaviour we'd expect here. For my part, since, in my case, the button's position is fixed to the top left of the screen, I just gave the popover a `max-height` and it scrolls internally.

The thing about the `position: fixed` fix is that while it fixes the erroneous scrolling, there are still elements in the popover that you can't access.

**Comment by chancestrickland** [comment]
If you can develop a simplified working prototype of something better without `MenuButton`, I'm happy to consider how we might account for this.
