### ISSUE TITLE
[Dialog] Focus on Formik form is locked on first input field

### ISSUE THREAD

**Issue by samselikoff** [reach/reach-ui#396]
## 🐛 Bug report

I think there's a strange interaction between Formik's `useFormik` hook and Reach Dialog's autofocus behavior.

I'm not sure if this is a Formik bug, but I wanted to open this issue here (1) in case others go searching, and (2) because it works with certain configurations of `<Dialog />`, but not others.

I also did some searching and found [this issue](https://github.com/reach/reach-ui/issues/267). It could be related.

### Current Behavior

When the `useFormik` hook is used in the _same_ component that renders a `<Dialog />`, there seems to be a locking focus behavior. The form inputs cannot be tabbed.

In the demo, you'll notice the first two examples work as expected: you can open the dialog, then tab through the inputs.

### Expected behavior

You should be able to tab through the inputs.

### Reproducible example
Here's a CodeSandbox: https://codesandbox.io/s/react-dialog-formik-bug-6762m

**Comment by chancestrickland** [comment]
I believe you are correct, the two issues are related. Formik fields trigger an onBlur handler that updates the field's state, re-rendering the component. Putting the activation handler in a `useCallback` fixes the issue here. I'll do some tests locally and, so long as I don't find any adverse side effects, I should be able to patch this up this week.

**Comment by chancestrickland** [comment]
Should be fixed here!

**Comment by samselikoff** [comment]
Awesome, thanks Chance!
