### ISSUE TITLE
[tooltip] open on click

### ISSUE THREAD

**Issue by felixmosh** [reach/reach-ui#402]
## ❓Question

I'm trying to open the tooltip on click, there is any option to do so?

**Comment by chancestrickland** [comment]
Tooltips do not open on click, so what you're looking for probably shouldn't be a tooltip but some sort of popover. It may sound a bit arbitrary but the pattern as it is currently established suggests that they should not appear on click because:
- Clicking a button should trigger its related functionality, which is likely unrelated to the button itself
- A tooltip exists ONLY to provide secondary information about the trigger or button's behavior, so clicking it to see context would be a bit redundant since you'd already know what the button does once you've clicked it

To be sure, there is active debate about the tooltip and it's not an established spec, but there is some consensus here that we're following. You can read more about the issue as it's ironed out over at https://github.com/w3c/aria-practices/issues/128

If you could provide your specific use case, I'm happy to guide you to a more appropriate path forward if I can!

**Comment by felixmosh** [comment]
Thank you for your response! 🙏🏼

My use-case is a question mark icon that explains the sentence it follows, on mobile i would like it to be clicked.

**Comment by chancestrickland** [comment]
Ahh, yeah...touch events. This is unfortunately still unsettled territory as far a11y is concerned for tooltips. As such, we've made a conscious decision not to implement at this time. Per our docs:

> Touch Events: Touch events are currently not supported. There's not a lot of research or examples of these types of tooltips on mobile. We have some ideas but need to validate them first before implementing. Please adjust your interfaces on mobile to account for this.

I'm hopeful the validation of these ideas will happen sooner rather than later. We're aiming for an audit by the middle of the year, but in the mean time you may need to adjust your approach. One alternative I might suggest is wrapping your tooltip around a button with an `onTouchEnd` handler that triggers a dialog with the info you need. Something like this might help: https://codesandbox.io/s/elastic-mcnulty-qzou7

**Comment by felixmosh** [comment]
Looks like over kill just for allowing a tooltip to be managed...

If I could manage the inner state (`isOpen`) of tooltip I could implement it without the need for `Dialog`

**Comment by chancestrickland** [comment]
I hear you. However our primary focus is getting accessibility right, and we don't currently have a settled answer for tooltips. As such we're not prepared to expose that as part of the API at this point.
