### ISSUE TITLE
[Slider+Tooltip] Misplaced tooltip issue

### ISSUE THREAD

**Issue by cheepo2109** [reach/reach-ui#404]
## 🐛 Bug report
Hey everyone 👋🏻
This bug is based on [this example](https://github.com/reach/reach-ui/blob/master/packages/slider/examples/with-tooltip.example.js)

### Current Behavior
Tooltip is misplaced when component is unmounted

[Giphy Link](https://gph.is/g/Z5nXpRo)

### Expected behavior
Tooltip shouldn't be misplaced when component in mounted again

### Reproducible example

[CodeSandbox Link](https://codesandbox.io/s/reach-slider-tooltip-uju7w)

### Your environment

| Software                 | Name/Version(s) |
| ------------------------ | --------------- |
| Reach-slider  | 0.6.2|
| Reach-tooltip| 0.6.3|
| React                    | 16.11.0 |
| Browser                  | Google Chrome |
| Assistive tech           | 
| Node                     |
| npm/yarn                 | yarn |
| Operating System         | MacOS Mojave|

**Comment by chancestrickland** [comment]
Tooltip uses @reach/rect to measure a DOM node, which it cannot do if the node is not mounted. When you call `useTooltip`, it needs a mounted node in order to work predictably (remember that you cannot call a hook conditionally, and we also do not re-render when a ref value changes).

There are two workarounds here:
1. Break the slider into a separate component
2. Use `Tooltip` as a wrapper component instead of the `useTooltip` hook

Example: https://codesandbox.io/s/reach-slider-tooltip-pkdbo

**Comment by cheepo2109** [comment]
Thanks a lot @chancestrickland!
