### ISSUE TITLE
Why the active tab panel has tabindex="0"?

### ISSUE THREAD

**Issue by akonsu** [reach/reach-ui#490]
## ❓Question
I have a set of tabs and a set of corresponding tab panels. As in your basic example. I noticed that the active tab panel has `tabindex="0"` attribute. Why is this needed? This makes the active panel tabbable. So when I use tabs inside a dialog along with a focus lock that lets me tab through all the controls in the dialog, the active panel receives its own focus before all the controls in it, as I tab through the dialog. Is there a way to fix that? I use the same `react-focus-lock` library that you use internally, if this matters.

**Comment by chancestrickland** [comment]
The active tab *should* absolutely be focusable. If you can spin up a repro in a code sandbox of illustrating the specific issue I'll be happy to reopen and let you know if there's a way to deal with your specific issue.

**Comment by akonsu** [comment]
Thanks! Your sample story "Tabs with arbitrary elements" demonstrates what I am talking about:
1. move the focus to the tab "One"
2. press Tab key
3. the focus goes away from the tab "One" to the tab panel, but you do not see this, there is no outline or any visual clue
4. press Tab key again
5. the button "yo" in the tab panel gets the focus

My question is why we have step 3 and why the focus does not go to the button "yo" right away when I press Tab key while the focus is on the tab "One", and whether it is possible to "fix" that, and most importantly, is this according to the accessibility recommendations and how this helps with accessibility?

**Comment by chancestrickland** [comment]
Ahh gotcha. So yeah, this is outlined in the ARIA spec and [reflected in their example](https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html).

> - Puts the tabpanel in the page Tab sequence.
> - Facilitates movement to panel content for assistive technology users.
> - Especially helpful if there are panels that do not contain a focusable element.

**Comment by hamfz** [comment]
For the non active tabs, with a negative tab index? How would they have be accessed without a tab index?

**Comment by chancestrickland** [comment]
@hamfz Inactive tabs are accessible with left/right arrow keys, as well as Home + End for quick toggling between first and last tabs https://www.w3.org/TR/wai-aria-practices-1.2/examples/tabs/tabs-1/tabs.html#kbd_label

**Comment by coreylight** [comment]
Some context for my use case:
https://codesandbox.io/s/reach-tabs-scroll-issue-wpunx?file=/src/App.tsx

We have an issue where an input is losing focus when it shouldn't (from our POV).
In the first example that's simple html. You can type something into the input, then grab the scroll bar in the `ul` element to scroll. Your input will not lose focus. (very paired down example of a combobox).

In the second example using Tabs component, when you grab the scroll bar you lose input focus. This is because for some reason grabbing the scroll focuses the tab.

Is it possible to consider opt in to the tabIndex? Or any other recommendations for this type of behavior?

**Comment by chaance** [comment]
@coreylight If you pass `tabIndex` to the panel it will override what we set internally. If you pass `null` it will remove the tabIndex altogether (TypeScript will complain, but you can cast as any or ignore the line if you'd like).

I don't think this is a great idea because of the aforementioned accessibility requirements. Another option would be to use `onFocus` and `onPointerDown` to figure out if the user is interacting with the scroller and, if so, re-focusing the input in that case. This is similar to how we manage focus in combobox when the user interacts with options in the popover.
