### ISSUE TITLE
chore: Prettier in git commit hook

### ISSUE THREAD

**Issue by ryanflorence** [reach/reach-ui#5]
We should have a githook that runs prettier so that all code committed is formatted.

I set it up in https://github.com/reach/router with `pretty-quick`

Would love somebody to tackle this :)

**Comment by sudarshang** [comment]
Claiming this one.

**Comment by sudarshang** [comment]
I am seeing an unrelated test failure after installing `pretty-quick`. I installed `pretty-quick` using

`yarn add --dev pretty-quick`

When I run `yarn test` after that I see the following test failure

```
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run test
lerna ERR! FAIL src/index.test.js
lerna ERR!   ● Test suite failed to run
lerna ERR!
lerna ERR!     Cannot find module 'react-test-renderer' from 'index.test.js'
lerna ERR!
lerna ERR!       1 | import React from "react";
lerna ERR!       2 | import ReactDOM from "react-dom";
lerna ERR!     > 3 | import renderer from "react-test-renderer";
lerna ERR!         | ^
lerna ERR!       4 | import Component from "./index";
lerna ERR!       5 |
lerna ERR!       6 | let snapshot = element => {
lerna ERR!
lerna ERR!       at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:221:17)
lerna ERR!       at Object.<anonymous> (src/index.test.js:3:1)
lerna ERR!
lerna ERR! Test Suites: 1 failed, 1 total
```

This happens because yarn deletes the `react-test-renderer` from `node-modules` while installing the `pretty-quick` package. Is this happening because we don't have `react-test-renderer` in package.json?

**Comment by sudarshang** [comment]
I still don't know why using `yarn add` or adding packages to package.json causes the above test failure. I got the above branch to work by modifying package.json before running `yarn install`.
