### ISSUE TITLE
New docs site

### ISSUE THREAD

**Issue by chancestrickland** [reach/reach-ui#511]
Issues with the current docs:
- We opted not to style very much because the library is style agnostic. A negative side effect here is that the website and our components don't look that impressive at a glance -- sad face!
- Screen reader and keyboard navigation is a little wonky. If you want to test the live examples, you gotta tab all over the place until you land on one. If you just want code examples, you gotta tab to them until you find one and then you don't really know what the code snippet is doing.
- Lacks some context for motivation and philosophy in some regards. The library has matured and we've learned a lot over time.

Initial thoughts:
- We still want to show that Reach is style agnostic, but we can still give them some life and show the flexibility of our approach. I'm thinking a themeable docs site that shows Reach components as various recognizable brands.
- Seeking feedback from SR users on successful, easy-to-navigate docs sites. Hoping I can get some good information, but I'm thinking about ways to improve this experience starting with keyboard navigation.

More to come in this issue!

**Comment by chancestrickland** [comment]
Also open to any feedback and ideas here. I've gotten some good initial info from Twitter, but broader community input is extremely welcome.

**Comment by raunofreiberg** [comment]
I think that the current website is ok! Although, I've gotten feedback from folks that the first impression can be daunting since it resembles the WAI-ARIA docs a lot. So, to people unfamiliar with Reach UI, it can seem unapproachable (?)

@chancestrickland I'm not sure if this is the kind of thing you were going for, but I got to playing around with the website locally and got something like this running:

![Screenshot 2020-05-18 at 23 07 06](https://user-images.githubusercontent.com/23662329/82254871-53314400-995c-11ea-8643-41cc07400c6e.png)

A few minor improvements:
- typography weights and colors
- dark code editor for better contrast and attention
- move the "link to X community" actions to the header (I didn't find Spectrum's logo 😄)
- rework sidebar (I don't feel too strongly about keeping it white, so we can keep the primary color for contrast)

**Comment by oyeanuj** [comment]
@chancestrickland I think all the items that you have mentioned here are great and would be super useful. I'd say that the biggest problem I've had with the site (almost every time) is that it is not easy to spot the examples, and distinguish them from everything else on the page. I hope that gets some TLC as well!
