### ISSUE TITLE
Shouldn't MenuItem accept a className? 🤔

### ISSUE THREAD

**Issue by ElForastero** [reach/reach-ui#547]
https://github.com/reach/reach-ui/blob/dbc04f15d0c5e585da9804a561e34ec5921ed38d/packages/menu-button/src/index.tsx#L481

Looks like `MenuItem` should be difined as
```typescript
export type MenuItemProps = Omit<MenuItemImplProps, "isLink"> & HTMLAttributes<HTMLElement>;
```

Am I right? I dindn't put an MR since I'm not sure.

In the docs we have this example:

```tsx
function Example() {
  return (
    <Menu>
      <MenuButton>
        Actions <span aria-hidden>▾</span>
      </MenuButton>
      <MenuList>
        <MenuItem className="red-highlight" onSelect={() => {}}>
          Start Video
        </MenuItem>
        <MenuItem className="red-highlight" onSelect={() => {}}>
          Start Screenshare
        </MenuItem>
      </MenuList>
    </Menu>
  );
}
```

**Comment by chancestrickland** [comment]
Not seeing an issue on my end. If you can create a reproduction in codesandbox I'll reopen.

**Comment by ElForastero** [comment]
@chancestrickland 
Yep... https://codesandbox.io/s/sad-water-9hmo7?file=/src/App.tsx

I'm getting the error when I'm trying to extend the default MenuItem.

The same thing happens with MenuLink.

![image](https://user-images.githubusercontent.com/5102818/79143998-3d65b780-7dcf-11ea-9b05-773cbfcb9ed8.png)

**Comment by cpmsmith** [comment]
Looks like the confusion here is because `MenuLink` accepts more props than just those in `MenuLinkProps`, thanks to `forwardRefWithAs`.

**Comment by chancestrickland** [comment]
Ah yeah, so that's true. Because of how we're internally inferring inherited props with `forwardRefWithAs` we don't add them as a union on the exported type. I'd like to support this but frankly I'm not sure exactly how to do it, since the union should be that of our own types and the props type of whatever element is passed to `as` (Yes it's div by default, but it might not be...and it might not even be a JSX tag, hence the hacky workaround `forwardRefWithAs`). 

Happy to take PRs that address this while still correctly inferring types correctly from the `as` prop, but in the mean time if you're creating your own wrapper component I'd go ahead and declare the union since you already know you're going to keep it a `div` (or an `a` for MenuLink).
