### ISSUE TITLE
Can I use ListBoxList without ListboxButton ?

### ISSUE THREAD

**Issue by akonsu** [reach/reach-ui#559]
Is it possible to create a menu by using `ListboxList` without the `ListboxButton` and `ListboxPopover` components? I need to implement a menu that will be shown "inline" inside an existing component. I do not need the button that I will need to click to see the dropdown, I need to show the contents of the dropdown as part of my component. I tried something like below, and it does show the menu, but the menu is not selectable. Please help.

    <ListboxInput>
      <ListboxList>
        <ListboxOption value="a">A</ListboxOption>
        <ListboxOption value="b">B</ListboxOption>
        <ListboxOption value="c">C</ListboxOption>
      </ListboxList>
    </ListboxInput>

**Comment by chancestrickland** [comment]
I don't even know what this would look like without a button. What triggers the popover if you don't have a button? Do you have a similar example in the wild you can point to so I can see what you're trying to create?

**Comment by akonsu** [comment]
To clarify, I do not need to trigger the popover. I just want to show what normally is in popover right away, when I render my component. I need to implement something similar to a context menu, you know, the menu that you get when you right click. Maybe this is close to what I am looking for: https://codepen.io/SitePoint/pen/MYLoWY There we have 3 lines at the bottom ("Go to grocery", "type some code", etc), each of these items has a custom context menu that you can see if you right click on an item. I want to implement something similar using `ListBoxList` to render the menu itself. The popup that will contain the menu will be mine, so I do not need the reach-ui popup. I hope this is a bit clearer...

**Comment by chancestrickland** [comment]
Ah yeah, so that won't work here as that isn't really a listbox. There is an important semantic difference between a listbox and a context menu.

We don't currently have a context menu component but I'd recommend looking more closely at `MenuButton`. You won't be able to build a context menu with it directly but the patterns you'll need to implement for the MenuList and MenuItems should look a lot more like that than Listbox. We may consider building a context menu in the future but it's not currently in the pipeline.
