### ISSUE TITLE
Multiple TabList not working

### ISSUE THREAD

**Issue by rubenmoya** [reach/reach-ui#573]
### Current Behavior

In the documentation, the example with the multiple `TabList` is not working:

![tabs](https://user-images.githubusercontent.com/905225/80924457-52f44e80-8d89-11ea-81e6-82329a61ab70.gif)

### Expected behavior

Both of the `TabList` should change the `TabPanel`

### Reproducible example

[CodeSandbox Reproduction](https://codesandbox.io/s/reachui-tablist-bug-p02ez)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |  @reach/tabs       | 0.10.1        |
| React            |         | 16.12.0        |
| Browser          |  Chrome | 80.0.3987.163 |
| Assistive tech   |         |         |
| Node             |         | v12.10.0        |
| npm/yarn         |   yarn      | 1.17.3        |
| Operating System | Windows | 10      |

**Comment by raunofreiberg** [comment]
I took a quick look here, and I think what happens is that `Tabs` are all index based, and there are four `Tab` components but only two `TabPanel` components:

```tsx
<Tabs>
  <TabList>
    <Tab>Uno</Tab> // 0
    <Tab>Dos</Tab> // 1
  </TabList>
  <div>Random</div>
  <TabPanels>
    <TabPanel>Uno</TabPanel>
    <TabPanel>Dos</TabPanel>
  </TabPanels>
  <TabList>
    <Tab>Uno</Tab> // 2
    <Tab>Dos</Tab> // 3
  </TabList>
</Tabs>
```

So, clicking on `Tab` 3 or 4 has no effect since there is no corresponding `TabPanel` with the same index.

It could be possible to switch panels via their content in this case (or somehow find duplicate tabs), but is this even a real use case we should hack around?

**Comment by rubenmoya** [comment]
Not sure what the answer to that is, but if we choose not to support that use case we should change the docs, since right now it's misleading:

> In fact, you could have tabs on both the bottom and the top at the same time.

**Comment by chancestrickland** [comment]
Oof, good catch. This is a bit of a regression since we completely changed how indexing works pretty significantly. The result is much more composable, but it does look like we lost this as a tradeoff. I'm going to remove it from the docs for the moment but I'd like to explore how we might make this work again.
