### ISSUE TITLE
reach/tooltip and emotion

### ISSUE THREAD

**Issue by imrandyk** [reach/reach-ui#590]
I am running into some issues using a styled component as a child to a tooltip. On hover the tooltip is no where near the item that should have the tool tip.

Here is a trimmed down repro of the issue.

https://codesandbox.io/s/priceless-violet-swel0

**Comment by raunofreiberg** [comment]
Hey 👋

I think you should not create a styled component in the render of `Button`.

Moreover, `styled(As)` is unnecessary since [all styled components from Emotion accept the `as` prop by default.](https://emotion.sh/docs/styled#as-prop)

If you move the creation of `StyledAs` outside the render, the problem is resolved:

https://codesandbox.io/s/thirsty-goldberg-fijly?file=/src/App.js
