### ISSUE TITLE
Better Documentation for useMenuButtonContext

### ISSUE THREAD

**Issue by JakeSchroeder** [reach/reach-ui#611]
## 📖 Documentation
the docs do not provide a use case of useMenuButtonContext and its difficult to understand how to use it with multiple instances of the Menu component.

**Comment by WilkinsKa1** [comment]
Can this please be reopened? I am also having trouble trying to implement `useMenuButtonContext`.

**Comment by daydream05** [comment]
@WilkinsKa1 I just figured it out!

For `useMenuButtonContext` to work, it has to be called in a component that is a descendant of the Menu component because the MenuContext.Provider lives inside the Menu.

<img width="458" alt="Screen Shot 2020-09-03 at 1 05 45 AM" src="https://user-images.githubusercontent.com/11723413/92073457-ad2a0e00-ed81-11ea-8360-234f5448be0c.png">

Here's an example code:

```jsx
const Button = () => {
  const { isExpanded } = useMenuButtonContext()

  console.log(isExpanded)
  return (
    <MenuButton>
      <span aria-label="Menu">
        <MobileBurger />
      </span>
    </MenuButton>
  )
}

export const MobileMenu = () => {
  return (
      <Menu>
        <Button />
        <MenuList
          className="slide-down"
        >
          <MenuLink href="#vision">Vision</MenuLink>
        </MenuList>
      </Menu>
  )
}
```
