### ISSUE TITLE
Can't copy text to clipboard from within a Dialog

### ISSUE THREAD

**Issue by donavon** [reach/reach-ui#626]
### Current Behavior

If I call [`copee`](https://github.com/styfle/copee)'s `toClipboard` from within an `onClick` on a button from within a Dialog, nothing is copied. I thought it might be related to React portals, but it works from a basic portal (see CodeSandbox example). 

I suspect that Dialog is somehow hijacking the event and my `onClick` is happening on a subsequent tick or something, thus making this a non "user-initiated" action.

### Expected behavior

The text will copy

### Reproducible example

See this [CodeSandbox](https://codesandbox.io/s/dank-flower-n3xij)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |     Dialog    |   0.10.5 (latest)      |
| React            |         |     16.12.0    |
| Browser          |    Brave     |   latest      |
| Assistive tech   |         |         |
| Node             |         |         |
| npm/yarn         |         |         |
| Operating System |     macOs    |     10.14.6    |

![image](https://user-images.githubusercontent.com/887639/85949887-576f5a80-b927-11ea-8538-d9321fe46a3a.png)

![image](https://user-images.githubusercontent.com/887639/85949929-85ed3580-b927-11ea-8851-e6b07d361143.png)

**Comment by ghostd** [comment]
Hi,

After some investigations, when i pass `true` to `disabled` of `FocusLock` it works:
https://github.com/reach/reach-ui/blob/98101d4448f3342196e0feb8a379d729936d30c3/packages/dialog/src/index.tsx#L180-L186

**Comment by indiesquidge** [comment]
@ghostd is correct in that the Dialog copy does not work because

> By default the dialog locks the focus inside it. Normally this is what you want. This prop is provided so that this feature can be disabled. This, however, is strongly discouraged. [[source][1]]

Which poses an issue for `copee` because that library [attaches a textarea to the document][2].

So you could either set `dangerouslyBypassFocusLock` to `true` (not recommended for accessibility reasons), or you could create your own copy to clipboard functionality that includes the hidden textarea within the modal itself, which is exampled [here][3].

[1]: https://reach.tech/dialog#dialogoverlay-dangerouslybypassfocuslock
[2]: https://github.com/styfle/copee/blob/89b86d417011aa3715be9cf3e27a4351bb6ad730/src/copee.ts#L13
[3]: https://codesandbox.io/s/epic-leaf-6hdiq

**Comment by donavon** [comment]
@indiesquidge, Thank you **so much** for your response. I've also realized that copee has a `fromElement` method as well.

I've taken your example and changed it as follows and it works. I know yours is simpler and doesn't require a 3rd party package, but I'd like to keep the actual copy code in copee for "single responsibility" reasons.

```js
          copee.fromElement(ref.current);
          // ref.current.select();
          // document.execCommand("copy");
```

I'm going to close this ticket. Thanks again for your help.
