### ISSUE TITLE
Tooltip types broken

### ISSUE THREAD

**Issue by evertbouw** [reach/reach-ui#660]
### Current Behavior

The components `Tooltip` and `TooltipPopup` are of type `any`

### Expected behavior

They should be typed as a component

### Suggested solution(s)

The .d.ts file contains `import("../../utils/src")`, this folder doesn't exist. Changing to `import("../../utils")` fixed the issue locally.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |    tooltip     |   0.11.0      |
| React            |         |     ^16.13.1    |
| Browser          |    n/a     |         |
| Assistive tech   |   n/a      |         |
| Node             |         |    14.8.0     |
| npm/yarn         |    yarn     |  1.22.4       |
| Operating System |   ubuntu     |     20.04    |

**Comment by karlhorky** [comment]
Wonder if it's because of the `ts-node --transpile-only` from https://github.com/reach/reach-ui/pull/654 ...

cc @chancestrickland

**Comment by travigd** [comment]
For `@reach/accordion` version `0.10.4`, `@reach/utils` is imported as `import("@reach/utils")` in the .d.ts files.

For `@reach/tooltip` version `0.11.0`, `@reach/utils` is imported as `import("../../utils/src")` in the .d.ts files.

TypeScript is complaining that it can't find the declaration for the latter, which means that `Tooltip` has type `any` since it is defined in terms of `ForwardRefExoticComponentWithAs`.

**Comment by chancestrickland** [comment]
I found the bug I introduced with the build overhaul. Hoping to have a patch either this afternoon or tomorrow!

**Comment by chancestrickland** [comment]
Should be fixed in 0.11.2. Let me know if there are any issues here!

**Comment by karlhorky** [comment]
@chancestrickland thanks!

Is the fix mostly in https://github.com/reach/reach-ui/commit/6b5fb4e27262a9656d2b29858acb4482ce925a2d and https://github.com/reach/reach-ui/commit/a8ef829e01cc6175f01abb6201b4f485cf5bfd37 ?

**Comment by chancestrickland** [comment]
[a8ef829](https://github.com/reach/reach-ui/commit/a8ef829e01cc6175f01abb6201b4f485cf5bfd37) was the one. I simplified the build from v0.10 and in the process consolidated the TS configs, and I forgot to make sure path aliases didn't make it into the build config. Build still passed locally and in CI because the `../../src` path resolved, but not so in the published packages. Would love to update CI to catch that, but I didn't have time to explore too much. Just wanted to get a fix out quickly!
