### ISSUE TITLE
ComboboxInput Does not accept an external value

### ISSUE THREAD

**Issue by higimo** [reach/reach-ui#677]
### Current Behavior

I use React hook state to store value.
```
<Combobox
	openOnFocus
	onChange={event => setValue(event.target.value)}
	onSelect={item => setValue(item)}
	value={know}
>
	<ComboboxInput
		placeholder="placeholder"
		autocomplete
		className="input"
	/>
	<ComboboxPopover>
		<ComboboxList>
			<ComboboxOption value="Hello" />
			<ComboboxOption value="Biiiig" />
		</ComboboxList>
	</ComboboxPopover>
</Combobox>
```

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/unruffled-einstein-z6ycv?file=/src/index.js)

### Your environment

plz, make bash command how this print? Write it in this template

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |         |         |
| React            |         |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             |         |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by indiesquidge** [comment]
Hey @higimo! Can you provide a bit more detail on what your issue is and what you expect the behavior to be?

By the looks of the snippet you included (and your CodeSandbox), you've included the `onChange` and `value` prop on the Combobox component, but you'll want to put those on the input, same as you would with a native React input. Check out the [Combobox docs][1] for more details on the props for the different parts of this compound component.

```diff
<Combobox
	openOnFocus
-       onChange={event => setValue(event.target.value)}
	onSelect={item => setValue(item)}
-       value={know}
>
	<ComboboxInput
		placeholder="placeholder"
		autocomplete
		className="input"
+               onChange={event => setValue(event.target.value)}
+               value={know}
	/>
	<ComboboxPopover>
		<ComboboxList>
			<ComboboxOption value="Hello" />
			<ComboboxOption value="Biiiig" />
		</ComboboxList>
	</ComboboxPopover>
</Combobox>
```

[1]: https://reach.tech/combobox

**Comment by mgostisha** [comment]
Hey @indiesquidge! We're running into an issue with this implementation. When you add the controlled `value` prop to the input, it causes the popover to stay open when you select a value. Here's a basic repro: https://codesandbox.io/s/intelligent-payne-0u1xp

We're trying to work around the same case as in #502, where we want to have the displayed be different from what data we want to use (in this case, display a name, but use the related ID. there can be duplicate values in the ComboboxList, but those are made clear to the user using a custom Combobox option). More than happy to open a PR, it looks like there's one open for #502, and handling just this would be at odds with the keyboard handling.

**Comment by indiesquidge** [comment]
Hi @mgostisha, I may be misunderstanding your issue … can you explain how #502 is related to what you're trying to do here?

The idea of #502 is about passing custom data from `ComboboxOption` to the onSelect handler, but your example sandbox does not have custom option data. You have a `ComboboxInput` with a `null` initial value (i.e. it's telling Reach that you want to treat the input as [uncontrolled][1]), a no-op input change handler (continuing the intent of having an uncontrolled component), but then attempts to change that uncontrolled value programmatically (i.e. in a _controlled_ way) based on an option selection.

Notice in your example that wiring things up this way, the user is initially able to type anything they want in the input (because at this point its an uncontrolled input … how you'd get back the user's input if they didn't select an option isn't clear). If the user does decide to select one of the options, you programmatically update the input value, telling Reach you actually want to control this value yourself now, which breaks the input. The user is no longer able to type or delete.

[1]: https://github.com/reach/reach-ui/blob/eb8773b897218d970d04b96923f61f88d9c5db07/packages/combobox/src/index.tsx#L454

**Comment by AlainYRS** [comment]
Running in a problem where everything loads as expected but the control is not ready on time and is being disabled when rendered but any reload enable it.

Console output:
`When loaded: console.log(ready) => false // Input component disabled
When reloaded: console.log(ready) => true  // Input component enabled`

I hope someone could guide me since I have lost 3 days with this problem.

Component call:
`            <AutocompleteComp data={{
                label:"Type your search",
                Placeholder:"Placeholder",
                delay:300,
                ReturnState:setAddressSelected, // State to retrieve user selection
                Libraries:["places"],
                Country:["ca","mx"],
                Types:['address'], //address, establishment, geocode, (cities), (regions)
                MyStyles:{ backgroundColor: "white", color: "black", borderRadius:"7px", padding: "3.5px", zIndex:"10"},
                ApiKey:process.env.NEXT_PUBLIC_COMPONENT_GoogleMap_geolocation_apiKey
              }}
            />`

Component code:
`import React from 'react'
import usePlacesAutocomplete, { getGeocode, getLatLng } from 'use-places-autocomplete'
import { GoogleMap,useLoadScript,Marker,InfoWindow } from "@react-google-maps/api";
import {Combobox,ComboboxInput,ComboboxPopover,ComboboxList,ComboboxOption} from "@reach/combobox";
import "@reach/combobox/styles.css";

function AutocompleteComp(props) {
    const libraries = (props.data.Libraries);

    const { isLoaded, isError} = useLoadScript({
        googleMapsApiKey: props.data.ApiKey,
        libraries
    });

    const {
        value,
        suggestions: { status, data },
        setValue,
        clearSuggestions,
        ready,
      } = usePlacesAutocomplete({
        callbackName: "Callback Function",
        requestOptions: {
          types: props.data.Types,//address, establishment, geocode, (cities), (regions)
          componentRestrictions: { country: props.data.Country },
          fields: ['address_component', 'adr_address', 'business_status', 'formatted_address', 'geometry', 'icon', 'name', 'permanently_closed', 'photo', 'place_id', 'plus_code', 'type', 'url', 'utc_offset', 'vicinity'],
        },
        debounce: props.data.delay,
      });
  
      const handleSelect = ({address}) => () => {
        setValue(address, false);
        clearSuggestions();
        try {
          const results = getGeocode({ address });
          const { lat, lng } = getLatLng(results[0]);
          ReturnState({ address: address, lat: lat, lng: lng, selected: results[0] })
          return ({ address: address, lat: lat, lng: lng, selected: results[0] });
        } catch (error) {
            console.error(`😱 Error:`, error);
        }
      };

      if(isLoaded){
        return (
          <label htmlFor="search">{props.data.label}
              <Combobox onSelect={handleSelect}>
                  <ComboboxInput style={props.data.MyStyles}
                      id="search"
                      value={value}
                      onChange={(e) => setValue(e.target.value)}
                      className="combobox-input"
                      placeholder={props.data.Placeholder}
                      autoComplete="off"
                      disabled={!ready}
                  />
                  <ComboboxPopover style={props.data.MyStyles}>
                      <ComboboxList style={props.data.MyStyles}>
                          {status === "OK" &&
                              data.map(({ place_id, description }) => (
                                  <ComboboxOption key={place_id} value={description}/>
                              ))}
                      </ComboboxList>
                  </ComboboxPopover>
              </Combobox>
          </label>
        )
      }
    }

export default React.memo(AutocompleteComp)`
