### ISSUE TITLE
Allow ComboboxPopover to be shown unconditionally

### ISSUE THREAD

**Issue by travigd** [reach/reach-ui#684]
### Current Behavior

Currently the combobox only shows the list (rendered via `<ComboboxPopover />`) when in _expanded_ state (i.e., when the user has started typing).

### Desired Behavior

I'd like a way to show the list unconditionally (I'm using the combobox as an extra-interactive `select` component so it makes sense to always show all the options).

### Suggested Solution

Respect the `hidden` prop on `<ComboboxPopover />` (currently, it always overwrites it with the value determined from the current combobox state).

https://github.com/reach/reach-ui/blob/51e163dcfc2b3654e5344b719398daa3775cab63/packages/combobox/src/index.tsx#L628-L640

Change to
```ts
hidden: props.hidden ?? !isExpanded
```

### Who does this impact? Who is this for?

Useful for people who are using Combobox as extra-interactive `<select />` component (which is mentioned as a use case in the docs).

### Describe alternatives you've considered

Status quo.

**Comment by indiesquidge** [comment]
Hey @travigd!

> I'd like a way to show the list unconditionally (I'm using the combobox as an extra-interactive select component so it makes sense to always show all the options)

Can you explain your use-case here a bit further, and what you mean by an "extra-interactive `<select />`"? If you'd like the always show all the options, perhaps the [MenuButton][1] or [Listbox][2] would suit your situation better?

> Useful for people who are using Combobox as extra-interactive `<select />` component (which is mentioned as a use case in the docs)

Can you link to which docs you are referring to? The [Reach docs on Combobox][3] mention "don't think of it like a `<select/>`, but more of an `<input type="text"/>` with some suggestions".

[1]: https://reach.tech/menu-button
[2]: https://reach.tech/listbox
[3]: https://reach.tech/combobox

**Comment by travigd** [comment]
Thanks for the reply. I see that bit of docs now - my bad. The part that I was referencing was under the [ComboboxList persistSelection](https://reach.tech/combobox#comboboxlist-persistselection) section (as an aside - would it be possible for the docs to do that thing where you hover over a subheading and get the option to make it a hash link that you can easily copy from the URL bar?).

> [The `persistSelection` prop] allows you to treat a Combobox more like a `<select>` than an `<input/>`, but be mindful that the user is still able to put any arbitrary value into the input, so if the only valid values for the input are from the list, your app will need to do that validation on blur or submit of the form.

For context, I'm trying to build something akin to the Notion insertion menu:
![Example](https://user-images.githubusercontent.com/773453/95380865-314d4500-089c-11eb-9c63-978d9ee70d29.gif)

I think it's definitely kind of a stretch away from the original purpose of the combobox component, but if I can make it work, I'd like to. :)

In particular, I particularly want the ability to filter based on the text that is being inputted and to have keyboard navigation as well. The combobox component already does all the fancy focus management so that I don't have to which is why I reached for it.

**Comment by indiesquidge** [comment]
> The part that I was referencing was under the ComboboxList persistSelection section

I think the docs wording in its description of Combobox acting like a select here is a bit confusing. As far as `persistSelection` renders Combobox similar to select, it is _only_ with regards to: "if an option's value matches the value in the input, it will automatically be highlighted and be the starting point for any keyboard navigation of the list" [(source)][1]. Similar to the behavior of opening the options list on a native select using the arrow keys.

<img src="https://user-images.githubusercontent.com/3409645/95390558-6eb8cf00-08aa-11eb-93f5-3991425d8b23.gif" width="50%" />

Thanks for the deeper explanation of what you're trying to build, the gif is helpful. Unfortunately, I'm struggling to consider a good implementation of this feature using a combobox, particularly because the full input value here is not determining the contents of the listbox, only the value after `/`.

One idea could be to create a combobox that's absolutely positioned within the outer input and only displays after e.g. ` /` shows up. You could focus the combobox input as soon as it renders and use the `openOnFocus` prop to display the results list immediately, and unmount the combobox as soon as an option is selected. The challenges here would be: a) knowing when to mount/unmount the nestled combobox and b) managing focus via refs between the combobox input and outer input on combobox mount/unmount.

I'd be curious if folks have other ideas to help here, but I'm guessing it would be difficult to implement that Notion feature using a combobox.

[1]: https://github.com/reach/reach-ui/blob/51e163dcfc2b3654e5344b719398daa3775cab63/packages/combobox/src/index.tsx#L718-L720

**Comment by travigd** [comment]
I have a basic implementation right now (it redirects focus into the combobox input), and I'm decently happy with it for now. My only complaint is the initial purpose of the issue: I don't want to wait for the user to type before showing them suggestions (i.e., rendering the popover unconditionally)

**Comment by indiesquidge** [comment]
If you focus the combobox input, shouldn't the `openOnFocus` prop display the popover without the user needing to type?

The larger issue here is that by the [WAI ARIA spec][1]—that Reach components [aim to comply][2] to—the popup is hidden by default and only displays when it is triggered to do so, i.e. some event needs to happen.

> The popup is hidden by default, i.e., the default state is collapsed. The conditions that trigger expansion -- display of the popup --are specific to each implementation. Some possible conditions that trigger expansion include:
>
> - It is displayed when the Down Arrow key is pressed or the Open button is activated. Optionally, if the combobox is editable and contains a string that does not match an allowed value, expansion does not occur.
> - It is displayed when the combobox receives focus even if the combobox is editable and empty.
> - If the combobox is editable, the popup is displayed only if a certain number of characters are typed in the combobox and those characters match some portion of one of the suggested values.

[1]: https://www.w3.org/TR/wai-aria-practices-1.2/#combobox
[2]: https://github.com/reach/reach-ui#development-plans

**Comment by travigd** [comment]
Ah it does - I tried that previously and it didn't work, but I suppose that was just because of something else going wrong. When I add it now, it opens as soon as it's focused. However, it does not **stay** opened if (e.g.) the user types, then backspaces.

**Comment by chaance** [comment]
I think this is probably outside the scope of our combobox for now. The Notion animation is super helpful but I'm honestly not sure if it's a combobox or not 😅 I'd have to investigate the pattern further, but it doesn't seem to be covered by the WAI ARIA guidelines as @indiesquidge mentioned.

**Comment by indiesquidge** [comment]
Related RE the popover staying open "if (e.g.) the user types, then backspaces": #709
