### ISSUE TITLE
[Combobox] Displaying a user-friendly label instead of value

### ISSUE THREAD

**Issue by raunofreiberg** [reach/reach-ui#725]
## ❓ Question

Consider this example:

```tsx
<ComboboxList>
  <ComboboxOption value="1">
     Apple
  </ComboboxOption>
</ComboboxList>
```

Currently, this would always show `1` in the input of Combobox.

Instead, I want `Apple` to be displayed in the Combobox.

Here's a sandbox with the current behaviour: https://codesandbox.io/s/sad-morning-4s7se?file=/src/App.js

Here's a sandbox with my attempt to hack around this: https://codesandbox.io/s/mystifying-darwin-uve6b?file=/src/App.js

**Comment by indiesquidge** [comment]
@raunofreiberg can you explain your use case further?

Depending on your use case, an outside data structure can be a good solution for organizing data if you need to access data alongside your ComboboxOption value. The only suggestion I could offer is to make your data an [object instead of an array][1] for constant lookup time upon selection, but even that isn't going to matter unless you have thousands of items to search through. 

Keep in mind that you likely want to keep your ComboboxInput value as separate state from your selection value, otherwise you'll run into controlled state issues (notice how in your second CodeSandbox the ComboboxPopover does not close upon option selection). [Here is an example][2] showing the separation between the two states.

There is an [outstanding PR][3] around custom combobox data you may wish to read through as well.

[1]: https://github.com/reach/reach-ui/pull/514#issuecomment-630504047
[2]: https://github.com/reach/reach-ui/blob/a1ed8e8a55cd4c76292cb9a5fe5697930cc3f6e7/packages/combobox/examples/controlled.example.js
[3]: https://github.com/reach/reach-ui/pull/628

**Comment by dimitrisnl** [comment]
@indiesquidge Not OP but consider the following structure

```js
{ id: '10', name: 'John', email: 'john@hey.com' }
```

```jsx
 <ComboboxOption key={person.id} value={person.id}>{person.name} - {person.email}</ComboboxOption>
```

- By selecting this element, we will get `10` in the input. That's not very nice.
- By using the `name` as the value, we get better feedback on what's selected, but it's impossible to get the `id`. The name could not be unique.

Is there something I'm missing? I just need a callback for the id of the selected item.

**Comment by indiesquidge** [comment]
> By using the name as the value, we get better feedback on what's selected, but it's impossible to get the id. The name could not be unique.

@dimitrisnl the fact that the name could not be unique is precisely why more information is necessary for the value. In your example you also use "name + email" for the visual value of the option because the name only would be ambiguous to a user here too.

So what if you used the same unique identifier, "name + email", as your `value`, and massaged your data in such a way to use that value to access the person's id?

```jsx
const people = [
  { id: "10", name: "John", email: "john@hey.com" },
  { id: "11", name: "Ella", email: "ella@hey.com" },
  { id: "12", name: "Kara", email: "kara@hey.com" },
  // etc
];

/* Creates an object keyed by "name + email" who's value is the whole person:
 * { 
 *   "John - john@hey.com": { id: "10", name: "John", email: "john@hey.com" },
 *   "Ella - ella@hey.com": { id: "11", name: "Ella", email: "ella@hey.com" },
 *   // etc
 * }
 *
*/
const peopleByIdentifier = people.reduce((acc, person) => {
  acc[`${person.name} - ${person.email}`] = person;
  return acc;
}, {});

function handleSelect(identifier) {
  const person = peopleByIdentifier[identifier]; // access to the full person object selected
  console.log(person.id);
}

<Combobox onSelect={handleSelect} aria-label="choose a person">
  <ComboboxInput />
  <ComboboxPopover>
    <ComboboxList>
      {Object.keys(peopleByIdentifier).map((nameAndEmail) => (
        <ComboboxOption key={nameAndEmail} value={nameAndEmail}>
          {nameAndEmail}
        </ComboboxOption>
      ))}
    </ComboboxList>
  </ComboboxPopover>
</Combobox>
```

![people](https://user-images.githubusercontent.com/3409645/126398072-b9636393-8d7e-425b-91d0-65ee39c3bd4d.gif)
