### ISSUE TITLE
Unable to animate AnimatedDialogContent's "translateY" in with "overflow: hidden"

### ISSUE THREAD

**Issue by ChrisBrownie55** [reach/reach-ui#746]
### Current Behavior

When using `@reach/dialog` with `react-spring`, the `AnimatedDialogContent` component — created with `animated(DialogContent)` — is unable correctly animate from `translateY(100%)` to `translateY(0%)` with `overflow: hidden` set on the `AnimatedDialogOverlay`. Instead, the `AnimatedDialogContent` appears at it's end position (`translateY(0%)`) and has some odd jank going on.

https://user-images.githubusercontent.com/19195374/107703683-9e754a80-6c81-11eb-9e99-e5b5757f57b1.mp4

### Expected behavior

I expected the `AnimatedDialogContent` to slide up from the bottom of the screen. I created an example of this without `@reach/dialog` to demonstrate what it should look like:

https://user-images.githubusercontent.com/19195374/107704003-2eb38f80-6c82-11eb-8f02-b106df354734.mp4

### Reproducible example

[CodeSandbox for Reach UI's Dialog reproduction](https://codesandbox.io/s/reach-dialog-translatey-animation-bug-reproduction-d4jme?file=/src/App.js)

[CodeSandbox for working example without Reach UI's Dialog](https://codesandbox.io/s/react-spring-translatey-from-bottom-dcht2?file=/src/App.js)

### Suggested solution(s)

I have no clue why this happens and I couldn't find any information by looking at the source code for the Dialog components.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |    @reach/dialog     |    0.13.0     |
| React            |    react, react-dom     |    17.0.1     |
| Browser          |    Chrome Beta, Chrome, Firefox     |  89.0.4389.40, 88.0.4324.150, 86.0b8   |
| Operating System |     Windows    |         |

**Comment by indiesquidge** [comment]
Hey there! Take a look at the console in your in your Reach reproduction sandbox. You'll notice that you forgot to include `import "@reach/dialog/styles.css";` to load Reach's default styles. If you include this import and remove your custom styles (save `overflow: hidden` on the overlay), you'll notice the animation behaves as expected (meaning your issue is caused by some of your custom styling).

![animated-modal](https://user-images.githubusercontent.com/3409645/108025280-72d8c400-6fe3-11eb-9c88-03b1ddd89166.gif)

Alternatively you could [explicitly opt out of Reach's default styles][1] and include only your own, just make sure you're adding all necessary styles that you're skipping.

You're also getting a console warning for skipping the required `aria-label` on your Dialog. I know this was just a sandbox, but for anything you plan on releasing to customers, please remember to include this for accessibility reasons :)

[Forked sandbox][2]

[1]: https://reach.tech/styling#skip-including-styles
[2]: https://codesandbox.io/s/reach-dialog-translatey-animation-bug-reproduction-forked-7xjrn?file=/src/App.js

**Comment by ChrisBrownie55** [comment]
@indiesquidge That's a different location so it doesn't reproduce the same bug. The animation I'm doing still has the same bug. Translating up does work when you don't overflow at all (aka you're starting in the middle instead of off-screen).

If you look at the "Expected behavior" section of my issue you'll see what was supposed to happen is that the modal starts completely off-screen and ends attached to the bottom of the screen. Importing the base styles does not fix the animation at all.

https://user-images.githubusercontent.com/19195374/108088500-25d60b80-703e-11eb-970b-b70199a6f978.mp4

[Modified forked sandbox that still reproduces the same issue while importing base styles](https://codesandbox.io/s/reach-dialog-translatey-animation-bug-reproduction-forked-eechz?file=/src/styles.css)

**Comment by indiesquidge** [comment]
@ChrisBrownie55 thanks for the further explanation. My initial comments were less about including Reach's default styles as the solution and more about some of the custom styling as the problem, but I overlooked the exactness of the your expected behavior, my mistake.

This appears to be an issue with `react-focus-lock`'s `FocusLock`, specifically the `autoFocus` prop. Here is a [fork of your sandbox][2] working example without Reach's Dialog showing the issue. `FocusLock` is used within Dialog, but you can get around it by passing true for the DialogOverlay's `dangerouslyBypassFocusLock`. If you do this, it is recommended that you [supply your own focus trap][1] to keep the tab sequence locked within the modal contents. It would be worth digging into that library to figure out which options suit your needs best while still keeping your implementation as accessible as possible.

[1]: https://github.com/indiesquidge/reach-ui/blob/c5234721d372e2ab2a7745475007605e78d18895/packages/dialog/src/index.tsx#L99-L103
[2]: https://codesandbox.io/s/react-spring-translatey-from-bottom-forked-2b9k4?file=/src/App.js

**Comment by indiesquidge** [comment]
@ChrisBrownie55 were you able to animate the Dialog to your liking? (Would love to know what solution you landed on!) Could we close this ticket?

**Comment by ChrisBrownie55** [comment]
@indiesquidge Hi, I haven't had the time to try adding in my own focus lock yet. I'll probably get around to it tomorrow. I'll update you with how it goes then.

**Comment by ChrisBrownie55** [comment]
@indiesquidge I figured out what I had to do lol. So the actual issue is that when you focus on the dialog while it's being animated (I'm still not sure why but it just seems to cause an issue). To fix it, I am bypassing the focus lock but then as soon as the animation is done, I'm enabling the focus lock.

```jsx
const [status, setStatus] = useState('focus-unlocked')
const transition = useTransition(isOpen, null, {
  /* animation values */
  onRest(isOpen, animationStatus) {
    if (animationStatus === 'update') // update means done I guess, react-spring docs don't really say much
      setStatus(isOpen ? 'focus-locked' : 'focus-unlocked') // if done opening, lock focus. if done closing, unlock focus
  }
})

return (
  <AnimatedDialogOverlay
    dangerouslyBypassFocusLock={status === 'focus-unlocked'} // if focus is unlocked, bypass the focus lock
    // other props omitted
  >
     {/* children omitted */}
  </AnimatedDialogOverlay>
)
```

**Comment by ChrisBrownie55** [comment]
I do feel like this information should be added to the animation section of the documentation though as it is not at all evident in any manner that I was supposed to do this.
