### ISSUE TITLE
I think clicking the input in a Combobox should open the list.

### ISSUE THREAD

**Issue by ProggerPete** [reach/reach-ui#758]
### Current Behavior

At the moment when you click on the input for a Combobox the list does not open.  If openOnFocus is set then the 1st click on the input will open the list.  While the input has focus there is no way of opening the list without using the keyboard.

### Desired Behavior

If openOnFocus is set, then clicking the input should also open the list.

### Suggested Solution

https://github.com/reach/reach-ui/pull/757

### Who does this impact? Who is this for?

Users who mostly interact via a mouse

### Describe alternatives you've considered

Rather than tying this behaviour to openOnFocus it could also have its own flag

**Comment by indiesquidge** [comment]
@ProggerPete can you further describe the situation you're trying to solve for? If I'm understanding correctly, you're talking about a state in which the input is focused but the popover is closed, e.g. directly after a user makes an option selection. At this point, a user is able to do all of the following to show the popover again:
- change the input
- press the up or down directional key
- tab away from (blur) and tab back to (focus) the input
- click away (blur) and click back to (focus) the input

What alternative way are you suggesting a user should have to open the popover?

**Comment by ProggerPete** [comment]
I'd like the popover to open when ever the user clicks the input, regardless of whether the input currently has focus.

This would better handle the common scenario where the user accidentally selects the wrong value and then immediately wants to change it.  With the current behaviour I think the user will get frustrated as having to click somewhere else before clicking will reopen the popover is not intuitive.

**Comment by indiesquidge** [comment]
Thanks for explaining @ProggerPete. That's definitely an interesting point. Playing around with some existing comboboxes on the web and some apps, I'm not finding that behavior anywhere—even the [WAI ARIA example comboboxes][1] do not exhibit it. Not that is is an exhaustive list, but the [WAI ARIA practices for a combobox][2] also don't mention it as a possible method for displaying the popup.

> With the current behaviour I think the user will get frustrated as having to click somewhere else before clicking will reopen the popover is not intuitive.

I'm curious why you believe the other methods of displaying the popover are not intuitive. Do you have an example of a popular combobox that behaves in the way you're talking about?

[1]: https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html
[2]: https://www.w3.org/TR/wai-aria-practices-1.2/#combobox

**Comment by ProggerPete** [comment]
A native select, which the combobox behaviour is partially derived from, reopens when clicked.

All of the examples on the Aria page reopen on when clicked.
https://www.w3.org/TR/wai-aria-practices-1.2/#examples-1

A search for react comboboxes gives:

https://jquense.github.io/react-widgets/api/Combobox/
Doesn't open when clicked, but displays a separate button that can be clicked.

https://react-select.com/home
Opens on click, also displays a separate button

https://www.telerik.com/kendo-react-ui/components/dropdowns/combobox/
Doesn't open on click, but displays a separate button that can be clicked.

https://react-combobox.netlify.app/demo
Opens on click

https://material-ui.com/components/autocomplete/
Opens on click, also displays a separate button

My search did not find any examples of a combobox that doesn't open on click without providing a specific button to open the list.

**Comment by indiesquidge** [comment]
There is a [ComboboxButton][1] that can be used in the way you're describing and showing in some of those examples. Regretfully, this is not included in the [Reach Combobox documentation][2]. Would love a PR to add it if you're up for it! Otherwise I can add that to my todo list.

[1]: https://github.com/reach/reach-ui/blob/3ca7fabf63eb3e0e188aa096c03674f01bf92db9/packages/combobox/src/index.tsx#L912
[2]: https://reach.tech/combobox

**Comment by ProggerPete** [comment]
I'll check out the button, giving the user an obvious way to reopen the list was my main concern so it seems likely this will be sufficient.

**Comment by ProggerPete** [comment]
I've played with this a bit, having a button helps, but this still feels cumbersome to me.

I guess my question is, under what circumstances do you think a user might click the input and be unhappy that the popover opened as a result.  Particularly given that openOnFocus is true.

**Comment by RandomDude123** [comment]
As far as i understand `openOnFocus` would be solving the issue once the input does not get focus after `SELECT_WITH_CLICK` event. Removing [this line](https://github.com/reach/reach-ui/blob/e1a6fba7042e1e023c4a3a4e7c15a13225500667/packages/combobox/src/index.tsx#L981) seems to do the trick. Comparing the current behaviour with [WAI ARIA example comboboxes](https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html) also makes me think that it is a bug?

**Comment by indiesquidge** [comment]
> under what circumstances do you think a user might click the input and be unhappy that the popover opened as a result.

When considering the extension of an API, I usually think "_under what circumstances is this absolutely necessary_" not "_why would someone be unhappy if this was added?_".

> Particularly given that openOnFocus is true, so the first time they click the input the popover does open.

Focus is an action; if the combobox is already focused when the user clicks on it again, `openOnFocus` should be a no-op—the element is already focused. The reason the popover opens the first time they click on the combobox is because we're transitioning _to_ a focused state (from a blurred state).

There have been [ideas floated][1] around exposing a setter for controlling the ComboboxPopover open state. If that concept were to be more thoroughly discussed and brought to fruition, you would be able to use it to build your own focus handler to open the popover on click even when it's already focused. But there is no guarantee of that API yet. Outside of that, I don't see something like an `openOnClick` existing for this component, given that the ComboboxButton can achieve that behavior and `openOnFocus` already behaves as intended.

Curious if you have other thoughts on this issue, @chaance.

[1]: https://github.com/reach/reach-ui/issues/726#issuecomment-767171553

**Comment by ProggerPete** [comment]
I think the combobox failing to open when clicked violates the rule of least surprise.

I like the reach combobox otherwise and the modification to make it work how I'd like is minimal, so I'll just use my fork.

Cheers for the good work you've done.
