### ISSUE TITLE
[combobox] Allow automatic selection of first option

### ISSUE THREAD

**Issue by eschaefer** [reach/reach-ui#766]
### Current Behavior

While typing into a `ComboboxInput`, no `ComboboxOption` elements are selected.

### Desired Behavior

While typing into a `ComboboxInput`, there should be an optional behavior to allow the first `ComboboxOption` element to be automatically selected.

### Suggested Solution

**Example 2: List Autocomplete with Automatic Selection** from the official ARIA examples shows the intended behavior:
https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html

Adding an `autoSelectFirstOption?: boolean` prop to the `Combobox` component would be a convenient solution.

### Who does this impact? Who is this for?

This impacts users looking to implement smoother auto-completion flows with a combobox.

### Describe alternatives you've considered

I have considered manually calling `focus()` on a ref of the first `ComboboxOption` but this does not result in the element being selected.

**Comment by dmamie** [comment]
+1

**Comment by logeekal** [comment]
Working on it.

**Comment by logeekal** [comment]
Hello @chaance, I have observed one conflict with the current functionality of combo-box while working on it. Currently, navigation changes the combo-box input value. Now based on the [aria practices link](https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html), It looks like currently something similar to example 3 is implemented. 

But based on personal experience, auto selecting first option should NOT change the value of input box as it changes the typing flow of the user.  So we have 2 options, either we go completely go with  : 

1. **Option 2**: Input value does not change on navigation or auto-selection and only changes on Pressing enter. which is a change from current functionality which changes the input on navigation.

2. **Option 3**: Input value also changes on auto-selection for 0th index but can be easily removable as show below.
![image](https://user-images.githubusercontent.com/7485038/113516655-bb404700-957b-11eb-9c7f-af52ab6b387f.png)

**Comment by dmamie** [comment]
@logeekal we've faced the exact same UX issue. 

in our humble opinion option 2 is more user-friendly. 

thanks so much for working on it! :)

**Comment by logeekal** [comment]
Completely agreed. Will start implementation.

Thanks for quick response.

**Comment by logeekal** [comment]
Hello @dmamie / @chaance  , I observed that combo-box has autocomplete Prop which will auto-complete the input value on navigation of the option list.

**Problem**: 
If we implement Option 2, then auto-complete option becomes irrelevant, because option 2 i.e. List Autocomplete with Automatic Selection will only auto-complete when the value is selected NOT when navigation occurs.

I am assuming we cannot remove autocomplete prop as it will be breaking change.

**Possible Solution**:
If user chooses 

- `autoComplete = true && autoSelectFirstOption=false`
  -  then current behavior remains unchanged as inline auto-complete on navigation will always work as today.

- `autoComplete=false && autoSelectedFirstOption=true`
  - then option 2. i.e. input value does not changes unless user navigates to that value and manually selects it.

- `autocomplete=true && autoSelectedFirstOption = true`
  - Inline auto-complete does work when user is navigating the options but NOT when we have auto-selected the first value.  The problem with this approach is that currently I am calling `transition(NAVIGATE,{options[0]})` to move to first option and state machine has no way to determine if navigation was user triggered or code triggered.


I will keep exploring and will post if I have more question.

**Comment by chaance** [comment]
Thanks @logeekal for the initial research here! I appreciate the nuance and attention to detail.

My initial thought is that what began as a few relatively simple boolean flags to denote certain behaviors around selection are starting to get pretty complicated when used together in unexpected ways. I'm wondering if it might make more sense to deprecate the existing `autoComplete` prop and use something like `autoCompleteMode` as an enum of options that describe these behaviors and prevent weird UX conflicts like the one you've raised.

**Comment by logeekal** [comment]
Thanks @chaance for your kind words and this elegant solution. This makes a lot of sense to me but I would like to expand on the implementation of `autoCompleteMode = "both"` as it is a little complex.

1. I think this particular ARIA example does not provide very good UX as it hides all other options when autocompleting. I think implmentation like below will be a better example ( sort of type-ahead): 
<img width="243" alt="image" src="https://user-images.githubusercontent.com/7485038/114342623-7197c380-9b5c-11eb-97d8-69fca4cd4fdf.png">

2. Secondly, this kind of auto-complete only works if what user has typed exactly matches the starting part of the result. So It gives rise to 2 cases: 

    **Case 1**, where if we have a found a result which is eligible for type-ahead, 
    - then that type-ahead should not affect the drop down suggestions, they should remain as it is.
    - Pressing Enter/Right arrow/TAB should complete the type-ahead, how-ever Enter and TAB should blur out of the field completely
    - Do we need mobile support, if yes, SWIPING RIGHT should also have same effect?
  
    **Case 2**, where if there is NO eligible candidate for type-ahead, 
    - then this mode should act similar to `autoCompleteMode='both'`.

**Comment by cocoral** [comment]
@logeekal Thanks for working on this request! We got a recent feature request to select the first option too.

Just noticed that in the ARIA example, there's actually an extra state before any option is selected, after the options dropdown shows up -- if the user pressed the up/down key to navigate the options, the dropdown box would keep displaying all the options, updating the input value; only after the user press enter/tab way/press left or right key the dropdown option would be actually 'selected', and all the other options will disappear.
