### ISSUE TITLE
Interop question between Tooltip and Modal

### ISSUE THREAD

**Issue by kylemh** [reach/reach-ui#790]
## ❓Question

I've got a button with a Tooltip that opens a Modal when clicked. When the modal is closed, focus state returns to that button causing the Tooltip to reappear. What are my options for making this less weird for seeing-eye users?

**Comment by chaance** [comment]
Might be something we need to fix internally. We already do that with `menu-button` for sure but I thought we did the same with `dialog`. Will take a look when I can!

**Comment by kylemh** [comment]
In this instance it's just a normal HTML button which opens the modal on click (not a menu button).

**Comment by chaance** [comment]
Ah yeah, so that might be a question for the Radix team in that case. Their tooltip is going to show up on focus, as it should, but they may have a mechanism for disabling that in some instances like this. The button does need to be focused when the dialog closes, else that would be a WCAG and usability problem.
