### ISSUE TITLE
[menu-button] Menu in dialog can be opened only after the second click with React v17

### ISSUE THREAD

**Issue by akirilchik** [reach/reach-ui#808]
## 🐛 Bug report
Hi guys, please take a look. Thanks in advance.

Menu in dialog can be opened only after the second click with React v17.

### Current Behavior

Menu in dialog can be opened only after the second click with React v17.

https://user-images.githubusercontent.com/59922593/121688134-c6f44080-cacb-11eb-8a63-d2c2a84f3a77.mov

### Expected behavior

Menu in dialog should be opened after the first click.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/reach-ui-issue-ttqjo?file=/src/reach-styles/index.js)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |       |   latest      |
| React            |         |     latest (17)    |
| Browser          |   Chrome      |    latest     |
| Assistive tech   |         |         |
| Node             |         |         |
| npm/yarn         |         |         |
| Operating System |   MacOs  Big Sur  |     11.4    |

**Comment by akirilchik** [comment]
Any news?

**Comment by chaance** [comment]
I haven't had a chance to look into this yet, but it's on my list for the next release.

**Comment by chaance** [comment]
Looks like it's fighting with `react-focus-lock` a bit, triggering a blur event that immediately reverts the menu button's state after the initial click. I'll need to investigate this further in the dependency.

**Comment by austsinovich** [comment]
How is this investigation? Any updates?

**Comment by chaance** [comment]
Found the problem, haven't had time to implement/test the solution. Menu popovers are portaled, so when they receive focus the focus-lock kicks in and immediately steals it back, which triggers the menu popover blur event and closes it before you ever see anything. 

`react-focus-lock` has a few techniques for handling portaled elements. If this is a priority for you, I'd happily take a PR if you have time to go down this rabbit hole before I do! https://github.com/theKashey/react-focus-lock#portals

**Comment by chaance** [comment]
Alright, so I spent some more time on this tonight and here's the deal.

With `react-focus-lock` there are features that make handling focus with nested portaled elements possible, but it would be quite tricky for us to integrate in a way that "just works" by default. This would require some additional work to come up with the right API, and frankly I just don't have enough time to dedicate to new features/APIs at the moment. Hopefully that changes in the future, but here we are 😄 

That said, here's my response + a solution:
- We can't currently support portaled popovers inside of `dialog` without major changes
- To nest `MenuButton` inside of dialog and prevent the double-click issue:
  - Set `portal` prop to `false` on either `MenuList` or `MenuItems` depending on the API you're using
  - Wrap `Menu` in a relative-positioned DOM element so that the popover is positioned correctly relative to the button

I've made changes for the next release that will allow `Menu` to accept an `as` prop to make the second step a little easier, but you can wrap it in your own DOM element just as well. I added an example `inside-dialog.example.tsx` that shows this working on the current dev branch, and I'll update the docs to make this our official solution.

**Comment by danielstreit** [comment]
I'm hitting this too. Just to connect the dots a bit, I believe the underlying issue is explored [here](https://github.com/theKashey/react-focus-lock/issues/134) in react-focus-lock.
