### ISSUE TITLE
[Combobox] input focus misbehaviour

### ISSUE THREAD

**Issue by danielsimao** [reach/reach-ui#897]
### Current Behavior

When selecting a combobox option with the mouse, the input loses focus and regains. This behavior makes input emit onBlur and onFocus after clicking the selection.

### Expected behavior

Input should not lose focus at any point from the previously described action.

### Reproducible example

https://codesandbox.io/s/cocky-kate-9q8fq?file=/src/App.tsx

Steps: Write "ap", select one option and observe console.log.

### Suggested solution(s)

Somehow we need to make the focus persist after selecting.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |         |    0.16.5     |
| React            |         |    17.0.2     |
| Browser          |         |     Chrome & Brave    |
| Assistive tech   |         |         |
| Node             |         |   14.17.5      |
| npm/yarn         |     yarn    |    1.22.11     |
| Operating System |     MacOS    |    MacOS     |

**Comment by indiesquidge** [comment]
@danielsimao I don't believe the current behavior is a bug. If a user clicked outside of a native input element, it will always blur the input. This is expected and specced browser behavior. Since we want to re-focus the input after a [selection click][1], doing so programmatically is our only option.

[1]: https://github.com/reach/reach-ui/blob/07d815040f95d192225bac7fff2432fb26f7f90b/packages/combobox/src/index.tsx#L1021
